title: Ben Godfrey
description: >-
  Hacker, Father, Techno Enthusiast
baseurl: ""
url: ""
github_username: afternoon

theme: minima
plugins:
  - jekyll-feed
permalink: /:year/:month/:day/:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
